name: "Podcast Generator"
author: "Duncan Kirogi"
description: "Generates a feed for a podcast from YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  description: The comiter's email address
  required: true
  default: ${{ github.actor }}@localhost
name:
  description: The committer's name
  reuired: true
  default: ${{ github.actor }}
  
  
